### ISSUE TITLE
error no info when build rom

### ISSUE THREAD

**Issue by thanhdatpd** [thanhdatpd/android_device_meizu_bicot#22]
[  0% 1/29145] /home/thanhdatpd/lineage/out/soong/host/linux-x86/bin/sbox --sandbox-path /home/thanhdatpd/lineage/out/soong/.temp --output-root /home/thanhdatpd/lineage/out/soong/.intermediates/vendor/lineage/build/soong/generated_kernel_includes/gen --copy-all-output -c 'make  -C  O=__SBOX_OUT_DIR__ ARCH= CROSS_COMPILE=" " headers_install' && touch /home/thanhdatpd/lineage/out/soong/.intermediates/vendor/lineage/build/soong/generated_kernel_includes/gen/.dummy_dep
FAILED: /home/thanhdatpd/lineage/out/soong/.intermediates/vendor/lineage/build/soong/generated_kernel_includes/gen/.dummy_dep 
/home/thanhdatpd/lineage/out/soong/host/linux-x86/bin/sbox --sandbox-path /home/thanhdatpd/lineage/out/soong/.temp --output-root /home/thanhdatpd/lineage/out/soong/.intermediates/vendor/lineage/build/soong/generated_kernel_includes/gen --copy-all-output -c 'make  -C  O=__SBOX_OUT_DIR__ ARCH= CROSS_COMPILE=" " headers_install' && touch /home/thanhdatpd/lineage/out/soong/.intermediates/vendor/lineage/build/soong/generated_kernel_includes/gen/.dummy_dep
make: *** O=/home/thanhdatpd/lineage/out/soong/.temp/sbox289271632: No such file or directory.  Stop.
sbox command (make  -C  O=/home/thanhdatpd/lineage/out/soong/.temp/sbox289271632 ARCH= CROSS_COMPILE=" " headers_install) failed with err "exit status 2"

**Comment by thanhdatpd** [comment]
fixed with lineage path folder

**Comment by jagogardiner** [comment]
Hi @thanhdatpd,
Was wondering how specifically you fixed this? 
Thanks.

**Comment by thanhdatpd** [comment]
> Hi @thanhdatpd,
> Was wondering how specifically you fixed this?
> Thanks.

you can see this commit, i already post above: https://github.com/thanhdatpd/android_device_meizu_bicot/commit/f6ad62bdb3960592f96b2c8877c4a0a9da0ea193

i change cmd to  cmd: "echo 'd'",
i dont know that cmd for what and do what, but after change it, it build done. no error.
