### ISSUE TITLE
build fail with vendor eror

### ISSUE THREAD

**Issue by thanhdatpd** [thanhdatpd/android_device_meizu_bicot#30]
[ 99% 1942/1943] /bin/bash -c "(if [ -d /home/thanhdatpd/lineage/out/target/product/bicot/system/vendor ] && [ ! -h /home/thanhdatpd/lineage/out/target/product/bicot/system/vendor ]; then echo 'Non-symlink /home/thanhdatpd/lineage/out/target/product/bicot/system/vendor detected!' 1>&2; echo 'You cannot install files to /home/thanhdatpd/lineage/out/target/product/bicot/system/vendor while building a separate vendor.img!' 1>&2; exit 1; fi ) && (ln -sf /vendor /home/thanhdatpd/lineage/out/target/product/bicot/system/vendor ) && (mkdir -p /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/ /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates && rm -rf /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"ext_mkuserimg=mkuserimg_mke2fs.sh\" >>  /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"fs_type=ext4\" >>  /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"system_size=4294967296\" >>  /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"extfs_sparse_flag=-s\" >>  /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"squashfs_sparse_flag=-s\" >>  /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"selinux_fc=/home/thanhdatpd/lineage/out/target/product/bicot/obj/ETC/file_contexts.bin_intermediates/file_contexts.bin\" >>  /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"verity_disable=true\" >>  /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"system_root_image=true\" >>  /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"root_dir=/home/thanhdatpd/lineage/out/target/product/bicot/root\" >>  /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"skip_fsck=true\" >>  /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (PATH=/home/thanhdatpd/lineage/out/host/linux-x86/bin/:\$PATH build/make/tools/releasetools/build_image.py /home/thanhdatpd/lineage/out/target/product/bicot/system /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/system_image_info.txt /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/system.img /home/thanhdatpd/lineage/out/target/product/bicot/system /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/generated_system_image_info.txt || ( mkdir -p /home/thanhdatpd/lineage/out/dist; cp /home/thanhdatpd/lineage/out/target/product/bicot/installed-files.txt /home/thanhdatpd/lineage/out/dist/installed-files-rescued.txt; exit 1 ) )"
FAILED: /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/system.img 
/bin/bash -c "(if [ -d /home/thanhdatpd/lineage/out/target/product/bicot/system/vendor ] && [ ! -h /home/thanhdatpd/lineage/out/target/product/bicot/system/vendor ]; then echo 'Non-symlink /home/thanhdatpd/lineage/out/target/product/bicot/system/vendor detected!' 1>&2; echo 'You cannot install files to /home/thanhdatpd/lineage/out/target/product/bicot/system/vendor while building a separate vendor.img!' 1>&2; exit 1; fi ) && (ln -sf /vendor /home/thanhdatpd/lineage/out/target/product/bicot/system/vendor ) && (mkdir -p /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/ /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates && rm -rf /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"ext_mkuserimg=mkuserimg_mke2fs.sh\" >>  /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"fs_type=ext4\" >>  /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"system_size=4294967296\" >>  /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"extfs_sparse_flag=-s\" >>  /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"squashfs_sparse_flag=-s\" >>  /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"selinux_fc=/home/thanhdatpd/lineage/out/target/product/bicot/obj/ETC/file_contexts.bin_intermediates/file_contexts.bin\" >>  /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"verity_disable=true\" >>  /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"system_root_image=true\" >>  /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"root_dir=/home/thanhdatpd/lineage/out/target/product/bicot/root\" >>  /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"skip_fsck=true\" >>  /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (PATH=/home/thanhdatpd/lineage/out/host/linux-x86/bin/:\$PATH build/make/tools/releasetools/build_image.py /home/thanhdatpd/lineage/out/target/product/bicot/system /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/system_image_info.txt /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/system.img /home/thanhdatpd/lineage/out/target/product/bicot/system /home/thanhdatpd/lineage/out/target/product/bicot/obj/PACKAGING/systemimage_intermediates/generated_system_image_info.txt || ( mkdir -p /home/thanhdatpd/lineage/out/dist; cp /home/thanhdatpd/lineage/out/target/product/bicot/installed-files.txt /home/thanhdatpd/lineage/out/dist/installed-files-rescued.txt; exit 1 ) )"
Non-symlink /home/thanhdatpd/lineage/out/target/product/bicot/system/vendor detected!
You cannot install files to /home/thanhdatpd/lineage/out/target/product/bicot/system/vendor while building a separate vendor.img!
ninja: build stopped: subcommand failed.
01:39:38 ninja failed with: exit status 1

**Comment by thanhdatpd** [comment]
fixed

**Comment by lucasponez** [comment]
How?

**Comment by thanhdatpd** [comment]
> How?


i didn't remember, sr. if u build for m6 note, just clone this repo - done

**Comment by lucasponez** [comment]
> > How?
> 
> i didn't remember, sr. if u build for m6 note, just clone this repo - done

Thank you, friend.
